layout_spectrum: 1
color:
  saturation: 0.09003085
  lightness: 0.6892011
  brandStrength: 0.8434994
  rhythmicContrast: 0.584174
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.3796952
name: 'Barrett Says:'
