collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.8434994
  lightness: 1
  brandColors:
    - '#B5AEA4'
    - '#FDE2CF'
    - '#8D5234'
    - '#1767A4'
    - '#C47767'
  rhythmicContrast: 1
typography_spectrum: 0.3796952
layout_spectrum: 1
name: 'Barrett Says:'
